language: php

env:
    - SYMFONY_VERSION="2.2.*"
    - SYMFONY_VERSION="2.3.*"
    - SYMFONY_VERSION="2.4.*"
    - SYMFONY_VERSION="dev-master"

# 'symfony/templating' is a hack for https://github.com/symfony/symfony/pull/8280 resulting in method access mismatch  
before_script:
    - COMPOSER_ROOT_VERSION=dev-master
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - composer install --dev

php:
  - 5.3
  - 5.4
  - 5.5
  
script: phpunit --configuration phpunit.xml.dist --exclude-group ""
